# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6312a08b040e8175938074d9454d2ead3a1f0a9f9171d25d401f309dc37f859a358924d826f35a765324d07dd9877900995572377014a0ac1cdc6982fc55436e

test:
  secret_key_base: 211a9daf774f19a5befc25cbd49565b77548fce48a450eb8f2689220c4697488759336996bef0347d683af77fa34566c0ffe8692ba129822d8d24384d5320324

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
